export const guitarTheoryTopics = [
  'e-minor-pentatonic',
  'g-major-pentatonic',
  'g-minor-pentatonic',
  'pentatonic',
  'blues',
  'c-form',
  'a-form',
  'g-form',
  'e-form',
  'd-form',
  'minor-forms',
  'chromatic-riffs',
  'major-scale',
  'major-scale-not-all-seven-degrees',
  'major-scale-chromatic-passing-tones',
  'triads',
  'major-chords-1-4-5',
  'minor-chords-2-3-6',
  'major-chords-1-4-5-string-5',
  'minor-chords-2-3-6-string-5',
] as const

export type GuitarTheoryTopic = (typeof guitarTheoryTopics)[number]

export const guitarTheoryTopicNames: Record<GuitarTheoryTopic, string> = {
  'e-minor-pentatonic': 'E Minor Pentatonic Scale',
  'g-major-pentatonic': 'G Major Pentatonic Scale',
  'g-minor-pentatonic': 'G Minor Pentatonic Scale',
  pentatonic: 'Pentatonic Scale',
  blues: 'Blues Scale',
  'c-form': '“C Form” Barre Chord',
  'a-form': '“A Form” Barre Chord',
  'g-form': '“G Form” Barre Chord',
  'e-form': '“E Form” Barre Chord',
  'd-form': '“D Form” Barre Chord',
  'minor-forms': 'Minor Forms',
  'chromatic-riffs': 'Chromatic Riffs',
  'major-scale': 'Major Scale',
  'major-scale-not-all-seven-degrees': 'Major Scale (Not All Seven Degrees)',
  'major-scale-chromatic-passing-tones':
    'Major Scale (Chromatic Passing Tones)',
  triads: 'Triads',
  'major-chords-1-4-5': 'Songs Based on I IV V',
  'minor-chords-2-3-6': 'Songs With ii iii vi',
  'major-chords-1-4-5-string-5': 'Songs I IV V (On String Five)',
  'minor-chords-2-3-6-string-5': 'Songs With ii iii vi (String 5)',
}
