export const guitarTheoryTopics = [
  'e-minor-pentatonic',
  'g-major-pentatonic',
  'g-minor-pentatonic',
  'pentatonic',
  'blues-scale',
  'c-form',
  'a-form',
  'g-form',
  'e-form',
  'd-form',
  'minor-forms',
  'chromatic-riffs',
  'major-scale',
  'major-scale-not-all-seven-degrees',
  'major-scale-chromatic-passing-tones',
  'triads',
  'major-chords-1-4-5',
  'minor-chords-2-3-6',
  'major-chords-1-4-5-string-5',
  'minor-chords-2-3-6-string-5',
  'e-major-root',
  'a-minor-root',
  'changing-pentatonic-scales',
  'blues',
  'ionian-mode',
  'dorian-mode',
  'lydian-mode',
  'mixolydian-mode',
  'aeolian-mode',
  'inverted-power-chords',
  'thirds',
  'sixths',
  'sixth-and-flat-seventh',
  'octaves',
  'minor-seven',
  'major-seven',
  'dominant-seven',
  'minor-seven-am-form',
  'e-form-major-seven',
  'c-form-add-9',
] as const

export type GuitarTheoryTopic = (typeof guitarTheoryTopics)[number]

export const guitarTheoryTopicNames: Record<GuitarTheoryTopic, string> = {
  'e-minor-pentatonic': 'E Minor Pentatonic Scale',
  'g-major-pentatonic': 'G Major Pentatonic Scale',
  'g-minor-pentatonic': 'G Minor Pentatonic Scale',
  pentatonic: 'Pentatonic Scale',
  'blues-scale': 'Blues Scale',
  'c-form': '"C Form" Barre Chord',
  'a-form': '"A Form" Barre Chord',
  'g-form': '"G Form" Barre Chord',
  'e-form': '"E Form" Barre Chord',
  'd-form': '"D Form" Barre Chord',
  'minor-forms': 'Minor Forms',
  'chromatic-riffs': 'Chromatic Riffs',
  'major-scale': 'Major Scale',
  'major-scale-not-all-seven-degrees': 'Major Scale (Not All Seven Degrees)',
  'major-scale-chromatic-passing-tones':
    'Major Scale (Chromatic Passing Tones)',
  triads: 'Triads',
  'major-chords-1-4-5': 'Songs Based on I IV V',
  'minor-chords-2-3-6': 'Songs With ii iii vi',
  'major-chords-1-4-5-string-5': 'Songs I IV V (On String Five)',
  'minor-chords-2-3-6-string-5': 'Songs With ii iii vi (String 5)',
  'e-major-root': 'Songs with E Major Root',
  'a-minor-root': 'Songs with A Minor Root',
  'changing-pentatonic-scales': 'Changing Pentatonic Scales',
  blues: 'The "Blues" Approach',
  'ionian-mode': 'Ionian Mode',
  'dorian-mode': 'Dorian Mode',
  'lydian-mode': 'Lydian Mode',
  'mixolydian-mode': 'Mixolydian Mode',
  'aeolian-mode': 'Aeolian Mode',
  'inverted-power-chords': 'Inverted Power Chords',
  thirds: 'Thirds',
  sixths: 'Sixths',
  'sixth-and-flat-seventh': 'Sixth and Flat Seventh',
  octaves: 'Octaves',
  'minor-seven': 'Minor Seven ("Em form")',
  'major-seven': 'Major Seven ("A form")',
  'dominant-seven': 'Dominant Seven ("A form")',
  'minor-seven-am-form': 'Minor Seven (Am form)',
  'e-form-major-seven': 'E Form Major Seven',
  'c-form-add-9': '"C Form" Add 9',
}
